// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG0jNDLIJXdwSdoWEYn7KZAv-B0tzyFsY',
    appId: '1:530051330326:web:01c2042b30e51c9ce3a037',
    messagingSenderId: '530051330326',
    projectId: 'petsrology',
    authDomain: 'petsrology.firebaseapp.com',
    storageBucket: 'petsrology.firebasestorage.app',
    measurementId: 'G-85KRLV53LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrHAb3K1jBUQg6zDwAVfTw4maIfoznk4',
    appId: '1:530051330326:android:876cf7c38c41bc3be3a037',
    messagingSenderId: '530051330326',
    projectId: 'petsrology',
    storageBucket: 'petsrology.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA05RaiZCxLize4CW07cJof0kFITYFvel8',
    appId: '1:530051330326:ios:24371bc369d411c4e3a037',
    messagingSenderId: '530051330326',
    projectId: 'petsrology',
    storageBucket: 'petsrology.firebasestorage.app',
    iosBundleId: 'com.example.petsrology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA05RaiZCxLize4CW07cJof0kFITYFvel8',
    appId: '1:530051330326:ios:24371bc369d411c4e3a037',
    messagingSenderId: '530051330326',
    projectId: 'petsrology',
    storageBucket: 'petsrology.firebasestorage.app',
    iosBundleId: 'com.example.petsrology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG0jNDLIJXdwSdoWEYn7KZAv-B0tzyFsY',
    appId: '1:530051330326:web:f3fab81ebcf751b4e3a037',
    messagingSenderId: '530051330326',
    projectId: 'petsrology',
    authDomain: 'petsrology.firebaseapp.com',
    storageBucket: 'petsrology.firebasestorage.app',
    measurementId: 'G-8NLBMWFTD6',
  );
}
